version: "3"

services:
  jenkins-docker:
    image: docker:dind
    privileged:
      true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - 2377:2376

  jenkins-built-in:
    # image: jenkins/jenkins:lts
    # image: jenkins/jenkins:2.492.3-jdk17
    build: ./built-in
    container_name: jenkins_sandbox
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50001:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro

  jenkins-agent:
    #image: jenkins/ssh-agent:jdk11
    build:
      context: ./ssh-agent-android
    container_name: jenkins_agent
    privileged: true
    user: root
    expose:
      - 22
    ports:
      - "2201:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBLIC_KEY}
    secrets:
      - ssh_agent_pubkey

  jenkins-agent-android:
    #image: jenkins/ssh-agent:jdk11
    build:
      context: ./ssh-agent-android

    container_name: jenkins_agent_android
    privileged: true
    user: root
    expose:
      - 22
    ports:
      - "2221:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBLIC_KEY}
    secrets:
      - ssh_agent_pubkey

  git-server-rockstorm:
    container_name: git_server_rockstorm

    image: rockstorm/git-server

    environment:
      SSH_AUTH_METHODS: "publickey"
    ports:
      - 2202:22

    volumes:
      - ./ssh-agent/.ssh/id_rsa.pub:/home/git/.ssh/authorized_keys
      - ../../../CI_CD/gitserver:/srv/git

  gitweb:
    image: rockstorm/gitweb

    volumes:
      - ../../../CI_CD/gitserver:/srv/git:ro

volumes:
  jenkins-data:
  jenkins-docker-certs:

secrets:
   ssh_agent_pubkey:
     file: ./ssh-agent/.ssh/id_rsa.pub