version: "3"

networks:
  frontend:
    driver: default
    ipam:
      driver: default
      config:
       - subnet: 172.18.0.0/24
         gateway: 172.18.0.1

services:
  jenkins-docker:
    image: docker:dind
    privileged:
      true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - 2377:2376

  jenkins-built-in:
    build: ./built-in
    container_name: jenkins_sandbox
    privileged: true
    user: root
    networks:
        frontend:
            ipv4_address: 172.18.0.2
    ports:
      - 8081:8080
      - 50001:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro

  jenkins-agent:
    build:
      context: ./ssh-agent
    container_name: jenkins_agent
    privileged: true
    user: root
    networks:
        frontend:
            ipv4_address: 172.18.0.3
    expose:
      - 22
    ports:
      - "2201:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBLIC_KEY}
    secrets:
      - ssh_agent_pubkey

  jenkins-agent-android:
    build:
      context: ./ssh-agent-android

    container_name: jenkins_agent_android
    privileged: true
    user: root
    networks:
        frontend:
            ipv4_address: 172.18.0.4
    expose:
      - 22
    ports:
      - "2221:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBLIC_KEY}
    secrets:
      - ssh_agent_pubkey
    volumes:
      - ./ssh-agent/.ssh/id_rsa:/home/jenkins/.ssh/id_rsa

  git-server-rockstorm:
    container_name: git_server_rockstorm

    image: rockstorm/git-server
    privileged: true

    environment:
      SSH_AUTH_METHODS: "publickey"

    networks:
        frontend:
            ipv4_address: 172.18.0.5
    ports:
      - 2202:22

    volumes:
      - ./ssh-agent/.ssh/id_rsa.pub:/home/git/.ssh/authorized_keys
      - ../../CI_CD/gitserver:/srv/git

  gitweb:
    image: rockstorm/gitweb
    privileged: true
    networks:
        frontend:
            ipv4_address: 172.18.0.6

    volumes:
      - ../../CI_CD/gitserver:/srv/git:ro

volumes:
  jenkins-data:
  jenkins-docker-certs:

secrets:
   ssh_agent_pubkey:
     file: ./ssh-agent/.ssh/id_rsa.pub